const surNames = [
    "Almeida",
    "Barbosa",
    "Cardoso",
    "Dias",
    "Fernandes",
    "Gomes",
    "Lima",
    "Martins",
    "Nogueira",
    "Oliveira",
    "Pereira",
    "Ribeiro",
    "Silva",
    "Souza",
    "Teixeira",
    "Vasconcelos",
    "Araujo",
    "Barros",
    "Castro",
    "Duarte",
    "Esteves",
    "Freitas",
    "Gonçalves",
    "Henriques",
    "Igrejas",
    "Jardim",
    "Klein",
    "Lopes",
    "Machado",
    "Neves",
    "Pacheco",
    "Queiroz",
    "Rezende",
    "Santana",
    "Tavares",
    "Uchoa",
    "Valente",
    "Xavier",
    "Zanetti"

    // You can add more options here...
];

export default surNames;
